services:
  postgres:
    image: postgres:18
    container_name: euroatlas-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: euroatlas
      POSTGRES_PASSWORD: euroatlas_password
      POSTGRES_DB: euroatlas_cargo

    ports:
      - "5433:5432"

    volumes:
      - euroatlas_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U euroatlas -d euroatlas_cargo',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  euroatlas_postgres_data: